name: Cache test
on: workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: ./.github/actions/cache
          
  restore:
    runs-on: ubuntu-latest
    needs: cache
    steps:
    - uses: actions/checkout@v4
    - name: Restore
      uses: ./.github/actions/restore

  release:
    runs-on: ubuntu-latest
    needs: restore
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - name: Release
      run: npx semantic-release
