name: Cache test
on: workflow_dispatch

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: ./.github/actions/cache
          
  restore:
    runs-on: ubuntu-latest
    needs: cache
    steps:
    - uses: actions/checkout@v4
    - name: Restore
      uses: ./.github/actions/restore
